### ISSUE TITLE
Add the ability to edit a book's title and/or author

### ISSUE THREAD

**Issue by id7604ug** [id7604ug/book_wishlist#10]

**Comment by id7604ug** [comment]
I have added the methods to change the author and book title but I am working on debugging them to work correctly. As I typed this I found out I forgot the self argument when creating the book object method.

**Comment by id7604ug** [comment]
By adding the self argument to the book object methods I created I fixed the bug I was getting and now the program runs correctly.

**Comment by id7604ug** [comment]
Bug: Ended up changing all book titles

**Comment by brendon21c** [comment]
This works just fine
